### PR TITLE
bluetooth: controller: Merge BT_HCI_VS_EXT into BT_HCI_VS

### PR DESCRIPTION
**Pull request by MarekPieta**
`18c23daee3317c8b4b9ed69f7d8c81112b5185f8` removes CONFIG_BT_HCI_VS_EXT. Align BLE controller configuration with the changes.

PR also aligns code after `484fe3f06c44de897ec0271d8cf36d52300627d7` was added to Zephyr.

Jira: NCSDK-27508

### CODE REVIEW

**Comment by MarekPieta** [comment]
@rlubos, please do not merge it yet. Waiting for reviews.

**Review by rick1082 — APPROVED** [review]

**Comment by rick1082** [comment]
Approved for the ISO part, will do an update for that project soon,

**Review by hermabe — APPROVED** [review]

**Review by ppryga-nordic — APPROVED** [review]
Checked two commits related to Bluetooth

**Review by KAGA164 — APPROVED** [review]

**Comment by rlubos** [comment]
Cherry-picked to the upmerge branch.

**Pull request closed without merging**
